name: Cypress Tests

on:
  push:
    branches: [main]
  pull_request:

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Run Cypress tests using cypress-io action
      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        with:
          config-file: cypress.config.ts
          start: ''
          wait-on-timeout: 120
          spec: |
            cypress/e2e/api/createEmployee.cy.js
            cypress/e2e/api/deleteEmployee.cy.js
            cypress/e2e/api/getEmployee.cy.js
            cypress/e2e/api/updateEmployee.cy.js
            cypress/e2e/api/login.cy.js
          record: false
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}

      # Step 5: Upload test artifacts if Cypress fails
      - name: Upload Cypress artifacts
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: cypress-artifacts
          path: |
            cypress/screenshots
            cypress/videos
